# Generated by Django 5.2.1 on 2025-06-20 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the faculty.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='A brief description of the faculty.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the department.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='A brief description of the department.', null=True)),
                ('faculty', models.ForeignKey(help_text='The faculty to which this department belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='Core.faculty')),
            ],
        ),
    ]
