# Generated by Django 5.2.1 on 2025-06-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0002_alter_department_options_alter_faculty_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the course.', max_length=100)),
                ('code', models.CharField(help_text='The unique code for the course.', max_length=10, unique=True)),
                ('description', models.TextField(blank=True, help_text='A brief description of the course.', null=True)),
                ('department', models.ForeignKey(help_text='The department to which this course belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Core.department')),
                ('faculty', models.ForeignKey(help_text='The faculty to which this course belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Core.faculty')),
            ],
        ),
    ]
