# Generated by Django 5.2.1 on 2025-06-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('100', '100'), ('200', '200'), ('300', '300'), ('400', '400'), ('500', '500')], default='100', help_text='The level at which the course is offered.', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='semester',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second')], default='First', help_text='The semester in which the course is offered.', max_length=10),
        ),
    ]
