# Generated by Django 5.2.1 on 2025-06-22 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_course_level_course_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='number_of_initiated_attendances',
            field=models.IntegerField(default=0, help_text='The number of initiated attendances for this course.'),
        ),
    ]
