# Generated by Django 5.2.1 on 2025-10-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AttendanceApp', '0002_attendancesession_initiator_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='instant_attendance_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='is_instant_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
