# Generated by Django 5.2.1 on 2025-06-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_course_number_of_initiated_attendances'),
        ('User', '0002_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses_taking',
            field=models.ManyToManyField(blank=True, help_text='Courses the student is currently enrolled in.', to='Course.course'),
        ),
    ]
